from __future__ import annotations

from app.sebi_orders_rag.directory_data.models import (
    BoardMemberRecord,
    DirectoryOfficeRecord,
    DirectoryPersonRecord,
    DirectoryReferenceDataset,
    OrgStructureRecord,
)
from app.sebi_orders_rag.repositories.structured_info import build_structured_info_snapshot
from app.sebi_orders_rag.structured_info.query_service import StructuredInfoQueryService


def build_structured_info_service() -> StructuredInfoQueryService:
    dataset = build_structured_info_dataset()
    return StructuredInfoQueryService(
        snapshot_loader=lambda: build_structured_info_snapshot(dataset),
        provider_name="canonical_structured_info",
    )


def build_structured_info_dataset() -> DirectoryReferenceDataset:
    return DirectoryReferenceDataset(
        people=(
            DirectoryPersonRecord(
                source_type="directory",
                source_url="https://www.sebi.gov.in/sebiweb/home/directory-of-sebi.jsp",
                canonical_name="Tuhin Kanta Pandey",
                designation="Chairman",
                role_group="chairperson",
                office_name="HEAD OFFICE, MUMBAI",
                email="chairman@sebi.gov.in",
                phone="022-40459999",
                date_of_joining="Mar 01, 2025",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="orgchart",
                source_url="https://www.sebi.gov.in/orgchart-grid.html",
                canonical_name="Shri. Tuhin Kanta Pandey",
                designation="Chairman",
                role_group="chairperson",
                email="chairman@sebi.gov.in",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="orgchart",
                source_url="https://www.sebi.gov.in/orgchart-grid.html",
                canonical_name="Amarjeet Singh",
                designation="Whole Time Member",
                role_group="wtm",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="orgchart",
                source_url="https://www.sebi.gov.in/orgchart-grid.html",
                canonical_name="Kamlesh Chandra Varshney",
                designation="Whole Time Member",
                role_group="wtm",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="orgchart",
                source_url="https://www.sebi.gov.in/orgchart-grid.html",
                canonical_name="Manoj Kumar",
                designation="Executive Director",
                role_group="executive_director",
                department_name="Investment Management Department (IMD)",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="directory",
                source_url="https://www.sebi.gov.in/sebiweb/home/directory-of-sebi.jsp",
                canonical_name="Nandita Rao",
                designation="Executive Director",
                role_group="executive_director",
                department_name="Corporation Finance Department (CFD)",
                office_name="HEAD OFFICE, MUMBAI",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="regional_offices",
                source_url="https://www.sebi.gov.in/department/regional-offices-43/contact.html",
                canonical_name="Amit Pradhan",
                designation="ED, Regional Director",
                role_group="regional_director",
                office_name="Northern Regional Office (NRO), New Delhi",
                email="amitp@sebi.gov.in",
                phone="011-69012960",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="directory",
                source_url="https://www.sebi.gov.in/sebiweb/home/directory-of-sebi.jsp",
                canonical_name="Rajudeen",
                designation="Deputy General Manager",
                role_group="staff",
                department_name="Investigation Department (IVD)",
                office_name="HEAD OFFICE, MUMBAI",
                email="rajudeen@sebi.gov.in",
                phone="022-40450088",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="directory",
                source_url="https://www.sebi.gov.in/sebiweb/home/directory-of-sebi.jsp",
                canonical_name="Dron Kumar Amrit",
                designation="Deputy General Manager",
                role_group="staff",
                department_name="Investigation Department (IVD)",
                office_name="HEAD OFFICE, MUMBAI",
                email="drona@sebi.gov.in",
                phone="022-40450089",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="directory",
                source_url="https://www.sebi.gov.in/sebiweb/home/directory-of-sebi.jsp",
                canonical_name="Kandunuri Lenin",
                designation="General Manager",
                role_group="staff",
                department_name="Investigation Department (IVD)",
                office_name="HEAD OFFICE, MUMBAI",
                email="lenink@sebi.gov.in",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="directory",
                source_url="https://www.sebi.gov.in/sebiweb/home/directory-of-sebi.jsp",
                canonical_name="Chitra Bhandari",
                designation="Assistant Manager",
                role_group="staff",
                department_name="Information Technology Department",
                office_name="HEAD OFFICE, MUMBAI",
                email="chitrab@sebi.gov.in",
                phone="022-40450111",
                staff_no="1668",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="orgchart",
                source_url="https://www.sebi.gov.in/orgchart-grid.html",
                canonical_name="Shri. Chitra Bhandari",
                designation="Assistant Manager",
                role_group="staff",
                department_name="Information Technology Department",
                office_name="HEAD OFFICE, MUMBAI",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="directory",
                source_url="https://www.sebi.gov.in/sebiweb/home/directory-of-sebi.jsp",
                canonical_name="Chitra M",
                designation="Assistant Manager",
                role_group="staff",
                department_name="Office of Investor Assistance and Education (OIAE)",
                office_name="Southern Regional Office (SRO), Chennai",
                email="chitram@sebi.gov.in",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="directory",
                source_url="https://www.sebi.gov.in/sebiweb/home/directory-of-sebi.jsp",
                canonical_name="Sachin Yadav",
                designation="General Manager",
                role_group="staff",
                department_name="Investment Management Department (IMD)",
                office_name="HEAD OFFICE, MUMBAI",
                email="sachiny@sebi.gov.in",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="directory",
                source_url="https://www.sebi.gov.in/sebiweb/home/directory-of-sebi.jsp",
                canonical_name="Sachin Kumar",
                designation="Assistant General Manager",
                role_group="staff",
                department_name="Office of Investor Assistance and Education (OIAE)",
                office_name="HEAD OFFICE, MUMBAI",
                email="sachinkr@sebi.gov.in",
            ).with_hash(),
            DirectoryPersonRecord(
                source_type="directory",
                source_url="https://www.sebi.gov.in/sebiweb/home/directory-of-sebi.jsp",
                canonical_name="Prasenjit Dey",
                designation="Deputy General Manager",
                role_group="staff",
                department_name="Investigation Department (IVD)",
                office_name="HEAD OFFICE, MUMBAI",
                email="prasenjitd@sebi.gov.in",
            ).with_hash(),
        ),
        board_members=(
            BoardMemberRecord(
                source_url="https://www.sebi.gov.in/sebiweb/boardmember/BoardMemberAction.do?doBoardMember=yes&lang=en",
                canonical_name="Tuhin Kanta Pandey",
                board_role="Chairman, SEBI",
                category="chairperson",
            ).with_hash(),
            BoardMemberRecord(
                source_url="https://www.sebi.gov.in/sebiweb/boardmember/BoardMemberAction.do?doBoardMember=yes&lang=en",
                canonical_name="Shri Amarjeet Singh",
                board_role="Whole-Time Member, SEBI",
                category="whole_time_member",
            ).with_hash(),
            BoardMemberRecord(
                source_url="https://www.sebi.gov.in/sebiweb/boardmember/BoardMemberAction.do?doBoardMember=yes&lang=en",
                canonical_name="Shri Kamlesh Chandra Varshney",
                board_role="Whole-Time Member, SEBI",
                category="whole_time_member",
            ).with_hash(),
            BoardMemberRecord(
                source_url="https://www.sebi.gov.in/sebiweb/boardmember/BoardMemberAction.do?doBoardMember=yes&lang=en",
                canonical_name="G Anantharaman",
                board_role="Part-Time Member, SEBI",
                category="part_time_member",
            ).with_hash(),
            BoardMemberRecord(
                source_url="https://www.sebi.gov.in/sebiweb/boardmember/BoardMemberAction.do?doBoardMember=yes&lang=en",
                canonical_name="Meena Hemchandra",
                board_role="Part-Time Member, SEBI",
                category="part_time_member",
            ).with_hash(),
        ),
        offices=(
            DirectoryOfficeRecord(
                source_type="contact_us",
                source_url="https://www.sebi.gov.in/contact-us.html",
                office_name="Southern Regional Office (SRO)",
                office_type="regional_office",
                region="south",
                address="7th Floor, 756-L, Anna Salai, Chennai - 600002, Tamil Nadu",
                phone="+91-44-28880222 / 28526686",
                fax="+91-44-28880333",
                email="sebisro@sebi.gov.in",
                city="Chennai",
                state="Tamil Nadu",
            ).with_hash(),
            DirectoryOfficeRecord(
                source_type="contact_us",
                source_url="https://www.sebi.gov.in/contact-us.html",
                office_name="Northern Regional Office (NRO)",
                office_type="regional_office",
                region="north",
                address="NBCC Complex, New Delhi - 110023",
                email="sebinro@sebi.gov.in",
                city="New Delhi",
                state="Delhi",
            ).with_hash(),
            DirectoryOfficeRecord(
                source_type="contact_us",
                source_url="https://www.sebi.gov.in/contact-us.html",
                office_name="SEBI Bhavan BKC",
                office_type="head_office",
                region="head_office",
                address="Plot No.C4-A, G Block, Bandra-Kurla Complex, Bandra (East), Mumbai - 400051, Maharashtra",
                phone="+91-22-26449000 / 40459000",
                email="sebi@sebi.gov.in",
                city="Mumbai",
                state="Maharashtra",
            ).with_hash(),
            DirectoryOfficeRecord(
                source_type="contact_us",
                source_url="https://www.sebi.gov.in/contact-us.html",
                office_name="SEBI Bhavan II BKC",
                office_type="head_office",
                region="head_office",
                address="Plot no. C-7, G Block, Bandra Kurla Complex, Bandra(E), Mumbai - 400051, Maharashtra",
                phone="91-22-26449000/40459000",
                email="sebi@sebi.gov.in",
                city="Mumbai",
                state="Maharashtra",
            ).with_hash(),
        ),
        org_structure=(
            OrgStructureRecord(
                source_type="orgchart",
                source_url="https://www.sebi.gov.in/orgchart-grid.html",
                leader_name="Amarjeet Singh",
                leader_role="Whole Time Member",
                department_name="Investment Management Department (IMD)",
                executive_director_name="Manoj Kumar",
                executive_director_email="manojk@sebi.gov.in",
            ).with_hash(),
            OrgStructureRecord(
                source_type="orgchart",
                source_url="https://www.sebi.gov.in/orgchart-grid.html",
                leader_name="Tuhin Kanta Pandey",
                leader_role="Chairman",
                department_name="Vigilance Department",
            ).with_hash(),
        ),
    )
